### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-doc#18]
Hi @stevehu,

I've been spending a bit of time reviewing the documentation generated from this repo, and it seems that there are a number of incomplete pages being hosted. It's making me question whether it's a good idea to release these pages on the main webpage as they could be confusion or frustrating for new users. 

As this is the interface to the library and likely the first impression that will be made with the users. I think we could benefit by approaching documentation from more of a quality vs quantity approach and avoiding releasing specific documentation until they are thoroughly reviewed and verified.
One important aspect could be that developers who are new to the framework being part of this review as their feedback could have been taken for granted by the authors and would be a valuable perspective.

I realize that this suggestion might slow down the documentation publishing process, however it could ultimately reduce effort by minimizing the number of questions being posed by users and even help us transition between developers.

Do you think this is something worth pursuing?

In either case, i will continue to go through the existing documentation and put together a list of some items that we could look to improve or fix. Hopefully this will help!

**Comment by stevehu** [comment]
It is a fantastic idea. There are so many documents I put in as a placeholder but never get a chance to work on them. We need to mark those as drafts so that they won't be released. There are issues found by the customers and we are fixing them along the way. We also need to review the syntax and grammar when we have a chance. For the documents I have reviewed, I am putting a tag in the header as "reviewed: true" to indicate that. Let me know if you have suggestions or recommendations.

**Comment by NicholasAzar** [comment]
Yeah the draft flag could certainly be a viable option. Originally i was just thinking the standard pr method..

So would the process for new pages then be:

1. New page added to develop with draft: true. (or existing incomplete pages updated)
2. Create a new issue referencing it, assigning it to others (and/or labeled as pending review)
3. Question/answer in the issue, changes commit in develop referencing the issue.
4. On complete, draft set to false.
